name: Sincronizar Tags de Upstream

on:
  workflow_dispatch: # Esto permite activar el botón manualmente

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar mi repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      name: Configurar repositorio original y empujar tags
        run: |
          git remote add upstream https://github.com/massgravel/Microsoft-Activation-Scripts.git
          git fetch upstream --tags
          git push origin --tags
